import { Injectable } from '@angular/core';
import { Case } from './case';

@Injectable({
  providedIn: 'root',
})
export class CaseService {
  constructor() {}

  caseList: Case[] = [
    {
      id: 1234567890,
      firstName: 'Shravani',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 68435154684,
      age: 300,
      sex: 'Female',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '5454545454',
      complaint: 'idk something',
    },
    {
      id: 84135166535,
      firstName: 'Shubham',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 6843513516,
      age: 30,
      sex: 'Male',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '9898989898',
      complaint: 'idk something',
    },
    {
      id: 1234567890,
      firstName: 'Shravani',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 68435154684,
      age: 300,
      sex: 'Female',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '5454545454',
      complaint: 'idk something',
    },
    {
      id: 84135166535,
      firstName: 'Shubham',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 6843513516,
      age: 30,
      sex: 'Male',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '9898989898',
      complaint: 'idk something',
    },
    {
      id: 1234567890,
      firstName: 'Shravani',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 68435154684,
      age: 300,
      sex: 'Female',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '5454545454',
      complaint: 'idk something',
    },
    {
      id: 84135166535,
      firstName: 'Shubham',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 6843513516,
      age: 30,
      sex: 'Male',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '9898989898',
      complaint: 'idk something',
    },
    {
      id: 1234567890,
      firstName: 'Shravani',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 68435154684,
      age: 300,
      sex: 'Female',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '5454545454',
      complaint: 'idk something',
    },
    {
      id: 84135166535,
      firstName: 'Shubham',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 6843513516,
      age: 30,
      sex: 'Male',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '9898989898',
      complaint: 'idk something',
    },
    {
      id: 1234567890,
      firstName: 'Shravani',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 68435154684,
      age: 300,
      sex: 'Female',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '5454545454',
      complaint: 'idk something',
    },
    {
      id: 84135166535,
      firstName: 'Shubham',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 6843513516,
      age: 30,
      sex: 'Male',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '9898989898',
      complaint: 'idk something',
    },
    {
      id: 1234567890,
      firstName: 'Shravani',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 68435154684,
      age: 300,
      sex: 'Female',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '5454545454',
      complaint: 'idk something',
    },
    {
      id: 84135166535,
      firstName: 'Shubham',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 6843513516,
      age: 30,
      sex: 'Male',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '9898989898',
      complaint: 'idk something',
    },
    {
      id: 1234567890,
      firstName: 'Shravani',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 68435154684,
      age: 300,
      sex: 'Female',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '5454545454',
      complaint: 'idk something',
    },
    {
      id: 84135166535,
      firstName: 'Shubham',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 6843513516,
      age: 30,
      sex: 'Male',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '9898989898',
      complaint: 'idk something',
    },
    {
      id: 1234567890,
      firstName: 'Shravani',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 68435154684,
      age: 300,
      sex: 'Female',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '5454545454',
      complaint: 'idk something',
    },
    {
      id: 84135166535,
      firstName: 'Shubham',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 6843513516,
      age: 30,
      sex: 'Male',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '9898989898',
      complaint: 'idk something',
    },
    {
      id: 1234567890,
      firstName: 'Shravani',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 68435154684,
      age: 300,
      sex: 'Female',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '5454545454',
      complaint: 'idk something',
    },
    {
      id: 84135166535,
      firstName: 'Shubham',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 6843513516,
      age: 30,
      sex: 'Male',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '9898989898',
      complaint: 'idk something',
    },
    {
      id: 1234567890,
      firstName: 'Shravani',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 68435154684,
      age: 300,
      sex: 'Female',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '5454545454',
      complaint: 'idk something',
    },
    {
      id: 84135166535,
      firstName: 'Shubham',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 6843513516,
      age: 30,
      sex: 'Male',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '9898989898',
      complaint: 'idk something',
    },
    {
      id: 1234567890,
      firstName: 'Shravani',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 68435154684,
      age: 300,
      sex: 'Female',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '5454545454',
      complaint: 'idk something',
    },
    {
      id: 84135166535,
      firstName: 'Shubham',
      lastName: 'Mhashelkar',
      date: new Date(),
      regNo: 6843513516,
      age: 30,
      sex: 'Male',
      address: 'idk somewhere',
      occupation: 'SDE',
      religion: 'Hindi',
      maritalStatus: 'Single',
      phone: '9898989898',
      complaint: 'idk something',
    },
  ];

  getAllCases(): Case[] {
    return this.caseList;
  }

  getCaseById(id: number): Case | undefined {
    return this.caseList.find((caseItem) => caseItem.id === id);
  }
}
